### ISSUE TITLE
Output in identifyable elements

### ISSUE THREAD

**Issue by bayleedev** [rabchev/web-terminal#12]
I'm trying to use this project to make integration tests for one of my projects. However it would make it a lot easier if I could use jquery to get things like the "last command" and "last output" which could be obtained by wrapping them in spans or divs.

This can somewhat be emulated by jquery now:

Last Command: 

``` javascript
jQuery('#content > [id^=ln]:eq(-2) #lnCnt').text()
```

Last Output:

``` javascript
$( "#content" )
  .contents()
    .filter(function() {
      return this.nodeType === 3;
    })
      .wrap( "<p></p>" )
      .end()
    .filter( "br" )
    .remove(); // wrap text nodes
text = [];
$('#content > [id^=ln]:eq(-2)').nextAll().slice(0, -1).each(function(i, el) {
    text.push($(el).text());
});
text.join('\n'); // output
```

**Comment by rabchev** [comment]
Hey Blaine,

Happy New Yer!

Sorry for the late response, I was on vacation.

I will try to push it within the next a few days. By the way, do you want to become a maintainer for this repo and the NPM? It would be nice to have someone else to help me with such tasks.
