### ISSUE TITLE
Web Terminal on https

### ISSUE THREAD

**Issue by Abubakar63** [rabchev/web-terminal#21]
I have web terminal running on my server on 4200 port so I can access it like http://ip-address:4200, I want to run it on https like https://ip_address:4200. How can I give ssl certificate information while starting it.

And also I have domain abc.com pointing to my server. So I need terminal to be running with domain name too like http://domain-name:4200

**Comment by rabchev** [comment]
Sorry for the late response.

The right way to handle this is to use reverse proxy, such as Nginx, in front of your service and do the SSL termination there.

**Comment by Abubakar63** [comment]
Thank you so much. I have already fixed this with same approach i.e. nginx reverse proxy.
